name: Release CSM-Replication
# Invocable as a reusable workflow
# Can be manually triggered
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
    inputs:
      option:
        description: 'Select version to release'
        required: true
        type: choice
        default: 'minor'
        options:
          - major
          - minor
          - patch
      images:
        description: 'Image names to be released. Example: dell-replication-controller,dell-csi-replicator'
        default: 'dell-replication-controller,dell-csi-replicator'
        required: true
jobs:
  csm-release:
    uses: harishp8889/test-common-github-actions/.github/workflows/csm-release-driver-module.yaml@main
    # uses: ./../test-common-github-actions/.github/workflows/csm-release-driver-module.yaml
    name: Release CSM Drivers and Modules
    with:
      version: ${{ github.event.inputs.option }}
      images: ${{ github.event.inputs.images }}
    secrets: inherit
